# Changes here will be overwritten by Copier
_commit: v1.1.1-23-g8c9aa68
_src_path: https://github.com/getscaf/template-starter.git
copier__author_name: Six Feet Up
copier__configure_repo: true
copier__create_repo: true
copier__description: ArgoCD Template
copier__email: info@sixfeetup.com
copier__enable_secret_scanning: true
copier__enable_semantic_release: true
copier__github_semantic_release_auth: github_app
copier__project_name_raw: ArgoCD Template
copier__project_slug: argocd_template
copier__repo_name: argocd-template
copier__repo_org: getscaf
copier__repo_provider: github
copier__repo_visibility: public
copier__task_runner: task
copier__version: 0.1.0
